// Connect HTML elements to JS
let compSelect = document.getElementById("dropdown");
let compInfo = document.getElementById("composerInfo");
let link1 = document.getElementById("link1");
let link2 = document.getElementById("link2");

// Add event listener
compSelect.addEventListener("change", function () {
  if (compSelect.value == "No Composer Selected") {
    compInfo.innerText = "Select a composer to learn more!";
    link1.innerHTML = ``;
    link2.innerHTML = ``;
  } else if (compSelect.value == "Florence Price") {
    compInfo.innerText = `Florence Price (April 9, 1887 - June 3, 1953) was an American composer, pianist/organist, and teacher. She was born in Little Rock, Arkansas and studied at the New England Conservatory of Music. Though she was born in Arkansas, she was active in Chicago starting in 1927. She was the first African American woman to be recognized as a symphonic composer as well as the first to have a composition played by a major orchestra. Throughout her career, she composed over 300 works, including 4 symphonies 4 concertos among other choral works, art songs, and other compositions. Before her time in Chicago, Price was the head of the music department at what is now Clark Atlanta University. As stated by Price's daughter, Price originally wanted to be a doctor but decided against it due to the societal difficulties involved with becoming a woman doctor. So instead, she became something perhaps even rarer: a Black woman composer of symphonies. The two pieces I've selected by Florence Price are "Symphony No. 1 in E Minor" and "Piano Concerto in D Minor". Enjoy!`;
    link1.innerHTML = `<a href=https://www.youtube.com/watch?v=9s4yY_A2A2k target="_blank">Price's Symphony No. 1 in E Minor</a>`;
    link2.innerHTML = `<a href=https://www.youtube.com/watch?v=zZKaL0fHzGM target="_blank">Price's Piano Concerto in D Minor</a>`;
  } else if (compSelect.value == "Irene Britton Smith") {
    compInfo.innerText = `Irene Britton Smith (December 22, 1907 - February 15, 1999) was an American classical composer and teacher. Smith originally hoped to study music at Northwestern, but her family unfortunately could not afford to do so. Instead, Smith studied to become a teacher at the Chicago Normal School. Shortly thereafter, she taught primary grades in public schools in Chicago. As for her musical career, she studied piano and took violin lessons. She was a violinist in the all-Black Harrison Farrell Orchestra from 1930-1931. For over a decade, Smith was a part-time student at the American Conservatory of Music, where she finally received a Bachelor of Music in 1943. She later completed graduate work at Juilliard, studying composition with Vittoria Giannini. She eventually received a Master of Music degree from DePaul University. Though she stopped composing in 1962, her pieces continued to be performed. The two pieces I've selected by Irene Britton Smith are "Sinfonietta" and "Fugue in G Minor for String Trio". Enjoy!`;
    link1.innerHTML = `<a href=https://www.youtube.com/watch?v=JSuHv9C8h1Q target="_blank">Smith's Sinfonietta</a>`;
    link2.innerHTML = `<a href=https://www.youtube.com/watch?v=LyGHZphHn7M target="_blank">Smith's Fugue in G Minor for String Trio</a>`;
  } else if (compSelect.value == "Nora Holt") {
    compInfo.innerText = `Nora Holt (November 8, 1884/5 - January 25, 1974) was an American critic, composer, singer, and pianist. She was the very first African American woman to receive a master's degree in music in the United States, which she did in 1918, earning her master's degree in music from Chicago Musical College. Holt composed over 200 works and was associated with the Harlem Renaissance. She also co-founded the National Association of Negro Musicians with Florence Price and others. Her mother encouraged her to start piano lessons, which sparked her love for music very early. Holt graduated as valedictorian from Western University in 1917 with a bachelor's degree in music. Holt's criticism career was with the Chicago Defender, one of the most famous and influential Black newspapers in America. Between 1923 and 1943, Holt halted her music criticism and she traveled and composed. After her time traveling, Holt launched and maintained several programs and festivals on radio stations. She received many awards throughout her career. The two pieces I've selected by Nora Holt are "Negro Dance, Opus 25 No. 1" and "The Sand-Man". Enjoy!`;
    link1.innerHTML = `<a href=https://www.youtube.com/watch?v=ZLdzoZ9V2A8 target="_blank">Holt's Negro Dance, Opus 25 No. 1</a>`;
    link2.innerHTML = ``;
  } else if (compSelect.value == "Helen Eugenia Hagan") {
    compInfo.innerText = `Helen Eugenia Hagan (January 10, 1891 - March 6, 1964) was an American pianist, teacher, and composer. Hagan studied piano with her mother and in public school in New Haven, Connecticut. She also began playing organ around age 9. Hagan became the first African American woman to receive a degree from Yale in 1912 when she graduated with her bachelor's degree in music. Also in 1912, she performed her own piece 'Piano Concerto in C Minor'. She received the Samuel Simmons Stanford scholarship to study in Paris and graduated from Schola Cantorum in 1914. Hagan performed as a concert pianist all over the United States from 1915 to 1918. Hagan also owned and operated a music studio in Morristown for at least a decade, making her the first African American woman admitted to the Morristown Chamber of Commerce. On September 29, 2016, Hagan's previously unmarked grave was unveiled at New Haven's Evergreen Cemetery. That day was also declared 'Women Making Music Day' by the New Haven mayor. The piece I've selected by Helen Eugenia Hagan is "Piano Concerto in C Minor". All her other works were lost. Enjoy!`;
    link1.innerHTML = `<a href=https://www.youtube.com/watch?v=EtXnYOJgFdc target="_blank">Hagan's Piano Concerto in C Minor</a>`;
    link2.innerHTML = ``;
  } else if (compSelect.value == "Lettie Alston") {
    compInfo.innerText = `Lettie Alston (1953 - 2014) was an American composer known for her piano work and a longstanding series of concerts called 'Lettie Alston and Friends'. She was born in Detroit and attended Wayne State University for her undergraduate and masters degrees. She received her doctorate in musical composition from the University of Michigan, making her the first African American woman to earn this degree from the University of Michigan. Alston has composed traditional works and electronic works. The two pieces I've selected by Lettie Alston are "Variations on 'Lift Every Voice and Sing'" and "Visions for Piano and Marimba". Enjoy!`;
    link1.innerHTML = `<a href=https://www.colorado.edu/project/hidden-voices/2020/04/25/variations-lift-every-voice-and-sing-lettie-beckon-alston target="_blank">Alston's Variations on "Lift Every Voice and Sing"</a>`;
    link2.innerHTML = ``;
  } else if (compSelect.value == "Regina Harris Baiocchi (active)") {
    compInfo.innerText = `Regina Harris Baiocchi (July 16, 1956) is an American musician, teacher, composer, and writer. Baiocchi was exposed to the arts from an early age and took guitar lessons at age 9. Baiocchi began composing at 10. She studied music in high school and church music programs, graduating from Roosevelt University with a Bachelor of Music degree in 1978. Baiocchi continued studies at the Illinois Institute of Technology, Northwest University, and graduated from New York University with a Master of Music degree in 1995. Baiocchi worked as a composer, writer, poet, high school teacher, audio quality control analyst, and a public relations director. She did it all. She composed plenty of works, as well as received many awards for her work. The two pieces I've selected by Regina Harris Baiocchi are "Azuretta" and "African Hands Concerto for Hand Drums and Orchestra". Enjoy!`;
    link1.innerHTML = `<a href=https://www.youtube.com/watch?v=zPAdjhBVZgU target="_blank">Baiocchi's Azuretta</a>`;
    link2.innerHTML = ``;
  }
});
